apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mycustom 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      namespace: chat-app
      labels: 
        app: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: amitkumar0441/chatapp-frontend:4
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
          



